services:
  - type: web
    name: task-in-web
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install --legacy-peer-deps --include=dev && npm run db:generate && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_PORT
        sync: false
      - key: MINIO_USE_SSL
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        sync: false
      - key: ELASTICSEARCH_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: ITHENTICATE_API_KEY
        sync: false
      - key: ITHENTICATE_API_URL
        sync: false
